### ISSUE TITLE
Server's failure to send confirmation e-mail, after a successful sign up, results in null value on server

### ISSUE THREAD

**Issue by loroz** [bigbassroller/launchpad#1]
1) I updated the .env file to include credentials for a gmail account, and brought LaunchPad online.
2) Then I navigated to the sign up page, filled in the fields, and pressed submit. I saw the "success" text.
3) Google blocked the transmission of the e-mail by the server, so it was never sent to my registration e-mail address.
4) LaunchPad now has issues with ```frontend/lib/auth.js```. The error thrown:

![image](https://user-images.githubusercontent.com/32349735/52034329-044c6a80-24dd-11e9-8096-3d58983e2dc3.png)

4.5) So I added a null check:
```
if (**decoded !== null &&** decoded.exp < Math.round(t / seconds)) {
        // console.log("token expired 🐱:")
        return false
    } else {
        // console.log("token not expired 🐱:")
        return decoded
    }
```

This ended up only passing the buck on null references:
![image](https://user-images.githubusercontent.com/32349735/52031830-36f16580-24d3-11e9-9493-1ff59ebbf72e.png)

5) I tried reinstalling the api and the frontend, but the same error occurs. 

I imagine the solution lies in being able to reset a bad or failed auth attempt.

**Comment by loroz** [comment]
6. Frontend console output: 

```
get intial props called from index
decoded �: null
 Math.round(t / seconds):� 1548913532
we have cookies(ctx)
cookies(ctx) : { token: 'undefined' }
this.props:  { className: 'container', isLoggedIn: null }
TypeError: Cannot read property 'username' of null
```

7. I'm looking at ``` cookies(ctx) : { token: 'undefined' }``` since the cookie is persisted.

8. I opened an incognito browser and that worked. I'm looking at the landing page again. This heavily suggests that the problem lies in the cookie. It looks like it contains an incorrect value for ```token```.

**Comment by mchavezi** [comment]
@loroz I think the issue stems from "3\. Google blocked the transmission of the e-mail by the server, so it was never sent to my registration e-mail address." and it setting a null cookie. Whats the error/reason Google blocks the transmission of the email?

**Comment by loroz** [comment]
Probably an administrative setting (I used a CCSF e-mail address) that blocks "suspicious activity."

**Comment by mchavezi** [comment]
Was able to confirm that it doesn't work with CCSF email by default. You need to <a href="https://myaccount.google.com/lesssecureapps" rel="nofollow noreferrer"><strong>Allow less secure apps to access account</strong></a> setting in your google account - by default this settings is <strong>off</strong> and you simply turn it <strong>on</strong>.
